### ISSUE TITLE
Nuxt composables don't work

### ISSUE THREAD

**Issue by peteromano** [storybook-vue/storybook-nuxt#33]
User-defined autoimported composables work, but composables like useNuxtApp() don't work (needs the Nuxt app context.)

I'm assuming this is still being developed though for 0.1.

**Comment by chakAs3** [comment]
Hi @peteromano indeed it is still in development. However all composables are working 
Have tried the demo repo 
soon a stable version will be available here how it looks like for now:

https://github.com/storybook-vue/nuxt/assets/711292/d643aa07-da68-4044-9ed5-91dea608ad26
