### ISSUE TITLE
Internal server error: Transform failed

### ISSUE THREAD

**Issue by LucaMargadant** [storybook-vue/storybook-nuxt#39]
When using the package with yarn its not working. There are a lot of different errors in my case it's mostly `cannot redeclare _resolveComponent`

On your stackblitz it looks like this:
```
/home/storybook-vue/storybook-nuxt-demo/pages/index.vue:131:6: ERROR: The symbol "_withScopeId" has already been declared
/home/storybook-vue/storybook-nuxt-demo/pages/index.vue:132:6: ERROR: The symbol "_hoisted_1" has already been declared
/home/storybook-vue/storybook-nuxt-demo/pages/index.vue:133:6: ERROR: The symbol "_hoisted_2" has already been declared
/home/storybook-vue/storybook-nuxt-demo/pages/index.vue:134:6: ERROR: The symbol "_hoisted_5" has already been declared
/home/storybook-vue/storybook-nuxt-demo/pages/index.vue:135:6: ERROR: The symbol "_hoisted_6" has already been declared
```

**How to reproduce**
1. Go to your stackblitz
2. remove pnpm lock
3. run ```yarn && yarn add react react-dom --dev```
4. run ```yarn storybook```

I guess It's now time for me to say goodbye to yarn and start to refactor my frontend codebase to use pnpm 😂
Still i wanted to leave this one here, so in case someone else having this problem knows that it's working when using pnpm.

**Comment by chakAs3** [comment]
I completely understand and agree. Even if migrating to pnpm takes me 10 days, I'm committed to doing it. The long-term benefits are worth it. It'll help me avoid the frustration and stress of dealing with various Yarn errors and other issues.

Im really wondering why devs still use Yarn ? like i was wondering why users still use Internet Explorer 9 hahahaha.

**Comment by chakAs3** [comment]
can you close thi? because hell i'm not going to fix Yarn shit ...😆

**Comment by LucaMargadant** [comment]
Haha, sure I will close it 😄  If you want I can add it to the docs later when I have time? 
So just that people know when using the package.

**Comment by DanHulton** [comment]
Hey @LucaMargadant, do you remember what the problem was that you were running into?  I'm also experiencing this, and can't leave yarn on account of it being able to install multiple architectures at once, while pnpm doesn't look like it will ever do this.  If I can figure out the issue, I can open a PR for it, so any additional information you remember about the specific cause you found would help!
