### ISSUE TITLE
Bug with Global Component Setting in Config

### ISSUE THREAD

**Issue by rezkileap** [storybook-vue/storybook-nuxt#57]
When I set the global component to true in the config, it's causing a bug and showing an error message.

`[vite:vue] At least one <template> or <script> is required in a single file component.
`

What's weird is that this happens even when none of the components are empty. I tried even on a new project too. I'm not sure if it's related, but I've saw a similar problem with Storybook Vue Vite.

https://github.com/storybookjs/storybook/issues/20024

`  components: [
    {
      global: true,
      path: '~/components',
      prefix: 'Mds',
    },
`

**Comment by rezkileap** [comment]
duplicate

**Comment by usamatariqnetshore** [comment]
any solution to this bug ?

**Comment by rezkileap** [comment]
not solution as right now but follow this issues instead 
https://github.com/storybook-vue/storybook-nuxt/issues/4
