### ISSUE TITLE
Windows - "pnpm storybook" leads to Error: Invariant failed: No builder configured in core.builder

### ISSUE THREAD

**Issue by Pecral** [storybook-vue/storybook-nuxt#61]
### Problems
Clean https://github.com/storybook-vue/storybook-nuxt-starter master
![image](https://github.com/storybook-vue/storybook-nuxt/assets/16672910/c8b8d079-65c0-40e3-84ac-fa41691bcec1)
Updating  "@storybook-vue/nuxt" to 0.1.0-rc.8:
![image](https://github.com/storybook-vue/storybook-nuxt/assets/16672910/3124eee9-fb75-4261-9327-0fe00c79c92b)

### How to reproduce
- On windows 10
- Nodejs LTS

Steps:
- Checkout https://github.com/storybook-vue/storybook-nuxt-starter master
- `pnpm install`
- `pnpm storybook`

The problem was reproducible on two different windows 10 machines.
On MacOs/Linux the issue does not occur.

Repository with "@storybook-vue/nuxt" to 0.1.0-rc.8: can be found here https://github.com/Pecral/storybook-nuxt-starter-no-builder-configured

**Comment by johnggreen** [comment]
Same errors here on Windows 11, running on Nodejs LTS and was able to run it fine on WSL (Ubuntu) same Nodejs LTS. For Wi ndows, I manually tried to add the below to my ```main.ts```
```javascript
core: { 
    builder: "@storybook/builder-vite",
  }
```

This got around the no builder found, however launched storybook with errors such as ```Expected your framework's preset to export a `renderToCanvas` field.```.

Also tried a demo that chakAs3 made at https://github.com/chakAs3/nuxt-storybook-module-demo which also reproduces the issue.
