### ISSUE TITLE
Version 0.2.0 released but not pushed to github?

### ISSUE THREAD

**Issue by filiphazardous** [storybook-vue/storybook-nuxt#84]
@chakAs3 I'm trying to solve https://github.com/nuxt-modules/storybook/issues/458 - but it seems the the latest release of this module on npmjs.com (0.2.0) isn't pushed to github. Cheers, and thanks for all the good work!

**Comment by filiphazardous** [comment]
If anyone else is interested in finding 0.2.0, it's available in this branch: https://github.com/storybook-vue/storybook-nuxt/compare/main...path-preview
:smile:

**Comment by chakAs3** [comment]
> @chakAs3 I'm trying to solve [nuxt-modules/storybook#458](https://github.com/nuxt-modules/storybook/issues/458) - but it seems the the latest release of this module on npmjs.com (0.2.0) isn't pushed to github. Cheers, and thanks for all the good work!

thanks for you words and help sorry i was busy this end of year you know the drill, i will be on the topic again happy to help

**Comment by chakAs3** [comment]
i pushed 0.2.1.  https://github.com/storybook-vue/storybook-nuxt/tree/v0.2.1
