### ISSUE TITLE
Storybook V8 / vue-component-meta support

### ISSUE THREAD

**Issue by AlexPaven** [storybook-vue/storybook-nuxt#92]
Hey guys,
do you plan to support the V8 beta or will you wait until it's released? I'm dying to try vue-component-meta instead of docgen - if you think it's easy to hack it together I would try it, but I'm not really knowledgeable enough with all the bits yet.

**Comment by chakAs3** [comment]
Yes I will soon update the package with v8 rc. To enable the vue-component-meta feature 🥳

**Comment by tobiasdiez** [comment]
v8 is now supported.
