### ISSUE TITLE
Versions since 0.2.1

### ISSUE THREAD

**Issue by daniluk4000** [storybook-vue/storybook-nuxt#94]
Hey there. Can't speak for everyone, but for our project all versions since 0.2.1 didn't work. 

0.2.5 just released without any commit or changelog in this repo, and it also doesn't build with brand new "RollupError: Expression expected" error.

Is this normal or are we doing something wrong?

**Comment by daniluk4000** [comment]
For now we'll keep skipping versions 

![image](https://github.com/storybook-vue/storybook-nuxt/assets/10450717/19f97050-e452-4532-80b4-c9a7f178bf23)

**Comment by chakAs3** [comment]
> For now we'll keep skipping versions 
> 
> 
> 
> ![image](https://github.com/storybook-vue/storybook-nuxt/assets/10450717/19f97050-e452-4532-80b4-c9a7f178bf23)
> 
> 

I apologize for the inconvenience I had to force some changes to fix there is no proper changelog for now. I will cleanup later once I got to stable version

**Comment by MiniDigger** [comment]
fwiw, I managed to get my storybook running using the `from-0.2.1` branch, after I updated all dependencies.
additionally, I also had to insert this line (else storybook didnt understand my vue files at all):
```diff
--- a/packages/storybook-nuxt/src/preset.ts
+++ b/packages/storybook-nuxt/src/preset.ts
@@ -101,6 +101,7 @@
           else {
             // Handle the case where the plugin with name 'vite:vue' was not found
             console.error('Plugin \'vite:vue\' not found in the array.')
+            plugins.push(vuePlugin())
           }
           baseConfig.plugins = plugins
           extendedConfig = mergeConfig(config, baseConfig)
```
do you want me to PR that?

**Comment by chakAs3** [comment]
> fwiw, I managed to get my storybook running using the `from-0.2.1` branch, after I updated all dependencies. additionally, I also had to insert this line (else storybook didnt understand my vue files at all):
> 
> ```diff
> --- a/packages/storybook-nuxt/src/preset.ts
> +++ b/packages/storybook-nuxt/src/preset.ts
> @@ -101,6 +101,7 @@
>            else {
>              // Handle the case where the plugin with name 'vite:vue' was not found
>              console.error('Plugin \'vite:vue\' not found in the array.')
> +            plugins.push(vuePlugin())
>            }
>            baseConfig.plugins = plugins
>            extendedConfig = mergeConfig(config, baseConfig)
> ```
> 
> do you want me to PR that?

i think this issue was already addressed in other commit, the history is not clean i'm sorry for that. you can open a PR i will review it that release a new tag.

**Comment by MiniDigger** [comment]
I tried v0.2.5 already, for the record, I am talking about this issue:
```
[15:43:47]  ERROR  Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
  Plugin: vite:import-analysis
  File: xxxxxx/node_modules/nuxt/dist/app/components/nuxt-root.vue:15:27
```
manually adding that line in the node_modules folder is enough to fix it for me. its not an issue with my project since I get it in the playground too, maybe something broke again with newer nuxt 🤷 
ill clean up my working tree and PR when I am home in a bit so you can take a look.

**Comment by MiniDigger** [comment]
https://github.com/storybook-vue/storybook-nuxt/pull/95

**Comment by alniv94** [comment]
> I tried v0.2.5 already, for the record, I am talking about this issue:
> 
> ```
> [15:43:47]  ERROR  Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
>   Plugin: vite:import-analysis
>   File: xxxxxx/node_modules/nuxt/dist/app/components/nuxt-root.vue:15:27
> ```
> 
> manually adding that line in the node_modules folder is enough to fix it for me. its not an issue with my project since I get it in the playground too, maybe something broke again with newer nuxt 🤷 ill clean up my working tree and PR when I am home in a bit so you can take a look.

![image](https://github.com/storybook-vue/storybook-nuxt/assets/89484751/69221862-6aec-4e72-b1e1-4129f131ba9f)
still got the same error

**Comment by MiniDigger** [comment]
0.2.5 doesnt include the PR yet

**Comment by alniv94** [comment]
Okay thanks, will wait for the release

**Comment by alniv94** [comment]
> 0.2.5 doesnt include the PR yet

I did pull ur pr yet the issue still present. Can u confirm? Thanks

**Comment by daniluk4000** [comment]
New error for me in 0.2.6...

![image](https://github.com/storybook-vue/storybook-nuxt/assets/10450717/6c983764-f727-4151-8787-02203fdfe740)

**Comment by Al-Rozhkov** [comment]
0.2.1 is the only version that works right now

**Comment by tobiasdiez** [comment]
> New error for me in 0.2.6...
> 
> ![image](https://private-user-images.githubusercontent.com/10450717/318057601-6c983764-f727-4151-8787-02203fdfe740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTgzNjAsIm5iZiI6MTcxNzIxODA2MCwicGF0aCI6Ii8xMDQ1MDcxNy8zMTgwNTc2MDEtNmM5ODM3NjQtZjcyNy00MTUxLTg3ODctMDIyMDNmZGZlNzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA1MDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTlmNjE2MmRiYjQ3YjgwNTBlNjJjMWY3NGFiN2RiMWMzOTI3OGQzNzIzZDkwNDNmOTUxMjc5MzU3ODc5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5WO3_zyl3ywojWrClUnLeoWX6cBKIDUaegVKnSeAxsI)

Could you please open a new issue (at https://github.com/nuxt-modules/storybook/) for this with more details. Thanks!

Closing as the original issue has been resolved.
