### ISSUE TITLE
feat: Support `@storybook/test`

### ISSUE THREAD

**Issue by shinGangan** [storybook-vue/storybook-nuxt#98]
### 📚 Description

Storybook V8 has been released and the library [`@storybook/test`](https://www.npmjs.com/package/@storybook/test) has been added.
This is a merger of `@storybook/jest` and `@storybook/testing-library`, and we propose to replace `@storybook/testing-library` with `@storybook/test`.

If the policy is okay, I would be happy to create a PR on my end.
( [Experimental branch](https://github.com/shinGangan/storybook-nuxt/tree/feat/add-storybook-test) )

### 👀 Ref

- https://storybook.js.org/blog/storybook-8/

> Storybook 8 also integrates Vite’s testing package, Vitest, as part of our new framework: @storybook/test. This new testing framework replaces two previous packages (@storybook/jest and @storybook/testing-library), enables the use of Vitest’s spy and expect, and has a smaller installation footprint. Learn more about [Storybook 8’s testing improvements](https://storybook.js.org/blog/storybook-test/?ref=storybookblog.ghost.io).

- https://storybook.js.org/blog/storybook-test/?ref=storybookblog.ghost.io

**Comment by shinGangan** [comment]
Hi @chakAs3 , I'd love to hear your comments when you have a time. 🙏

**Comment by chakAs3** [comment]
Sure @shinGangan go ahead with the PR 👍 thanks

**Comment by shinGangan** [comment]
@chakAs3 

OK, thanks for the comment! 👍 
I will create a PR later, please review when you have a time. 🙏
